---
- name: Config hosts
  hosts: cluster
  tasks:
    - name: Install Docker
      become: true
      block:
        - name: Add universal repo
          ansible.builtin.apt_repository:
            repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
            state: present

        - name: Install additional packages
          ansible.builtin.apt:
            name:
              - ca-certificates
              - curl
            update_cache: true
            cache_valid_time: 86400

        - name: Create keyrings folder
          ansible.builtin.file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: Add Docker's official CPG key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /etc/apt/keyrings/docker.asc
            mode: '0644'

        - name: Add repo to apt
          ansible.builtin.apt_repository:
            repo: >
              deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update_cache: true
            filename: docker

        - name: Install Docker-ce
          ansible.builtin.apt:
            name: docker-ce
            update_cache: true

        - name: Check Docker
          ansible.builtin.service:
            name: docker
            state: restarted
            enabled: true

    - name: Install Docker-compose
      become: true
      block:
        - name: Get latest docker-compose version from github
          ansible.builtin.uri:
            url: "https://api.github.com/repos/docker/compose/releases/latest"
            body_format: json
          register: page

        - name: Install Docker-compose
          ansible.builtin.get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-linux-x86_64"
            dest: /usr/local/lib/docker/cli-plugins
            mode: '0755'

    - name: Complete the installation
      become: true
      block:
        - name: Add user to group docker
          ansible.builtin.user:
            name: "{{ ansible_user }}"
            group: docker
            append: true

        - name: Reboot
          ansible.builtin.reboot:
